### PR TITLE
Create 2020-12-16-UnetStack-paper-on-Residual-Energy-Model.md

### PR DESCRIPTION
**Pull request by manuignatius**

### CODE REVIEW

**Review by mchitre — COMMENTED** [review]
For it to be a meaningful post, perhaps need a bit of commentary (event 2-3 sentences is fine, outlining how it fits with UnetStack) rather than just reproducing the abstract from IEEE. Otherwise maybe just tweet it.

**Comment by Florie25** [comment]
I added the link to the UnetStack website.

**Review by Florie25 — APPROVED** [review]

**Review by AnneThKu — APPROVED** [review]

**Review by notthetup — CHANGES_REQUESTED** [review]
As @mchitre pointed out. Maybe some comment instead of just copy-pasting the abstract.

**Comment by manuignatius** [comment]
I will add a short blurb as soon as I get a chance to read the paper.

**Review by notthetup — APPROVED** [review]

**Review by mchitre — APPROVED** [review]

**Pull request merged**
