### PR TITLE
Revamping About page

### PR DESCRIPTION
**Pull request by AnneThKu**
- The photos are dummy.
- The text needs to be updated for `OUR COMPANY`, `OUR JOURNEY`, `OUR TEAM`

### CODE REVIEW

**Review by manuignatius — DISMISSED** [review]

**Comment by manuignatius** [comment]
Pending customer testimonials.

**Comment by AnneThKu** [comment]
@Florie25 has contacted a few customers for the testimonials, but we haven't received any yet.

**Comment by AnneThKu** [comment]
@Florie25 @notthetup please find the revamped about page in https://subnero.com/test-products/about/ for review.

**Review by Florie25 — DISMISSED** [review]

**Review by notthetup — CHANGES_REQUESTED** [review]
Too many files to review. Please ensure only the files which are changed as a part of this PR are included in this request.

**Review by notthetup — DISMISSED** [review]

**Review by Florie25 — DISMISSED** [review]

**Review by notthetup — DISMISSED** [review]

**Comment by notthetup** [comment]
Is this ready? Or should we convert this PR to a draft?

**Review by Florie25 — APPROVED** [review]

**Pull request merged**
