### PR TITLE
Create 2018-02-08-SWAN-used-in-SG-water-management.md

### PR DESCRIPTION
**Pull request by Florie25**
I'm not sure if the picture will be the correct size. Is there a way to view the post before creating the pull request?

### CODE REVIEW

**Comment by notthetup** [comment]
It doesn't. You'll need to upload the image file to the images directory.

Screenshot 2020-05-14 15 33 31

**Comment by notthetup** [comment]
"Is there a way to view the post before creating the pull request?" <- yes there is but you'll have to run [Jekyll](https://jekyllrb.com/) on your computer. :(

**Comment by Florie25** [comment]
> "Is there a way to view the post before creating the pull request?" <- yes there is but you'll have to run [Jekyll](https://jekyllrb.com/) on your computer. :( <- that sounds complicated :(

**Comment by Florie25** [comment]
> It doesn't. You'll need to upload the image file to the images directory. <- I thought I had done it.
Let me double check.

**Comment by Florie25** [comment]
I uploaded the picture in the Master branch instead of the one created for the post.
Does the one in the Master branch need to be deleted?
Or can I upload the picture in the ASEAN post now?

**Comment by AnneThKu** [comment]
You can upload the image in the ASEAN branch also.

**Comment by Florie25** [comment]
The image has now been uploaded the correct branch. What does it look like?

**Comment by AnneThKu** [comment]
image

Also please change the `source` from `https://theaseanpost.com/article` to `https://theaseanpost.com` as the former link is not valid and hence the `Travis checks` are failing.

**Comment by Florie25** [comment]
The link for the source has been changed.

**Review by AnneThKu — APPROVED** [review]

**Review by notthetup — APPROVED** [review]

**Pull request merged**
