### PR TITLE
Adding pulse post for the SwanViz UI and CSSSR

### PR DESCRIPTION
**Pull request by AnneThKu**
image

### CODE REVIEW

**Review by notthetup — APPROVED** [review]
All good, can we fix the CI build issues?

**Comment by esthertanhj** [comment]
Please update the post based on the [document](https://docs.google.com/document/d/13JPe1smyWI4IkYAQ_R55zrRcpWnf1TfA7OwnmqLaKDk/edit?usp=sharing)  which contains changes suggested by CSSSR.

**Comment by AnneThKu** [comment]
The pulse link for 19-01-2018 post (https://gearforgesoftware.com/iot-weekly-podcast/iot-weekly-episode-8-podcast/) is also broken. This podcast episode does not seem to be available in the playlist(https://www.youtube.com/channel/UC_jIbCn9Dev2RmqNQ25Vs4Q/playlists)  also.

**Review by esthertanhj — APPROVED** [review]

**Comment by AnneThKu** [comment]
The build issue is related to broken podcasts link in Pulse page. The issue will be tracked in https://github.com/subnero1/subnero1.github.io/issues/151.

**Pull request merged**
