### PR TITLE
Adding new page for Distributors

### PR DESCRIPTION
**Pull request by AnneThKu**

### CODE REVIEW

**Comment by manuignatius** [comment]
1. Only 4 distributors listed, whereas we have 6. Missing ones are (logo added to page):
- [Yottec](https://yottec.com/), India
- [Optimos](https://www.optimosgroup.com/), Australia

2. Seabreath & Wuxu Smartsea is missing phone number and email id
3. Updated all logos with transparent backgrounds (pngs).
4. Can we have fixed size tiles?
Screen Shot 2021-09-11 at 11 22 45 PM
5. Update `Training & Support` to just `Support` to avoid bleeding to next line. Same with `Contact Us` -> `Contact`

**Review by manuignatius — CHANGES_REQUESTED** [review]
Comments indicated above.

**Comment by manuignatius** [comment]
Additional comments
1. Smartsea  tech link is wrong
2. Make clicking links (not images) open in new window too
3. Add email ids links? (using mailto tag)

**Comment by AnneThKu** [comment]
1. Yottec and Optimos added.
2. Updated for SmartSea. Still I couldnt find for SeaBreath. Checking with Florie for their details.
4. Changed to fixed tiles.
5. I understand this comment is because of the overflow, but just to check the `Support` was changed to `Training & Support` as per this issue https://github.com/subnero1/subnero1.github.io/issues/81.  Do you want to revert this change?
6. Corrected SmartSea link, removed links from images and added mailto for all emails.

Question:
7.  Do we need 2 links for "Become our distributor" and "Let us know". ?

**Comment by manuignatius** [comment]
4. Sure, you can change it to just support. (same for contact)
7. You can remove the link on `Let us know` and keep the button.

**Comment by manuignatius** [comment]
Also, I noticed that there is no link on the image now, is that intentional?

**Comment by manuignatius** [comment]
Can we list either a single phone number or in multiple lines for wuxi smartsea? It looks a bit odd now.

Also, use standard format with `+` for phone numbers. Some of them start with `0`, some have hyphens and some have spaces.

**Comment by AnneThKu** [comment]
Please find the screenshot of the Distributor page.

Screenshot 2021-09-13 at 2 32 57 PM

Screenshot 2021-09-13 at 2 33 02 PM

**Comment by AnneThKu** [comment]
> Also, I noticed that there is no link on the image now, is that intentional?

This was removed as per the "Additional comments",   "2. Make clicking links (not images) open in new window too"

**Comment by manuignatius** [comment]
> > Also, I noticed that there is no link on the image now, is that intentional?
> 
> This was removed as per the "Additional comments", "2. Make clicking links (not images) open in new window too"

Clicking on images/loog was working as expected (opening in new window). Just needed to fix that for the links.

**Comment by manuignatius** [comment]
> Please find the screenshot of the Distributor page.
> 
> Screenshot 2021-09-13 at 2 32 57 PM
> 
> Screenshot 2021-09-13 at 2 33 02 PM

Grey too light, hard to see :(

**Comment by AnneThKu** [comment]
- Updated phone number format
- Updated map image:
Screenshot 2021-09-13 at 5 45 03 PM

**Review by manuignatius — APPROVED** [review]

**Review by Florie25 — APPROVED** [review]

**Comment by manuignatius** [comment]
Screen Shot 2021-09-13 at 6 29 47 PM
Can you please overlay the icons on the map?

**Comment by notthetup** [comment]
@AnneThKu You can consider using https://developer.mozilla.org/en-US/docs/Web/HTML/Element/map for the clickable image bits.

**Comment by AnneThKu** [comment]
Added icon overlay and clickable areas in the map.

**Comment by notthetup** [comment]
Why do we need a separate file for the each distributor? Can't we have a single data file with all the distributors info? And then loop over the array for both the image maps and the cards?


https://jekyllrb.com/docs/datafiles/

**Review by notthetup — CHANGES_REQUESTED** [review]
Commented 👆🏽

**Comment by AnneThKu** [comment]
Moved distributor info to data file and removed the separate files

**Review by notthetup — APPROVED** [review]

**Pull request merged**
