### PR TITLE
Faqpage

### PR DESCRIPTION
**Pull request by jjophi**
New FAQ page

Add FAQ page #125
Screenshot 2023-08-20 at 11 52 20 AM

### CODE REVIEW

**Comment by manuignatius** [comment]
I have reviewed and updated the content. One comment thought, there is a large spacing between sections (see attached screenshot), any chance to reduce it?

Screenshot 2023-08-20 at 14 00 07

Also, can you add this as a section in the "training and support" page under documentation and add the "training and support" to the top menu?

Once done, you can push this to the staging website for others to review. For doing that, you just need to set your origin to "https://github.com/subnero1/website-staging" and push the branch. Later, the website will be live here: https://subnero.com/website-staging/

We get others to review the faq content before pushing this website live.

**Comment by esthertanhj** [comment]
image

On the above image,

1) Is it possible to show the entire wording instead of "..." in the categories section, or perhaps shorten it to "Hardware" and "Software & Unetstack" instead, for example?

2) Is it possible to combine several sections together so there are not so many categories? This might be easier for the user to navigate to the right section - 
- "General" has only 1 question, would it be better to combine with "Commercial" ? 
- Is there an overlap between the "Other Features" and "Hardware" section such that they can be combined?

**Comment by manuignatius** [comment]
@esthertanhj
- For 1, 2, yes, we will need to refine the sections and the content.
- For 3, yes, we can combine commercial to general and remove commercial.
- Sure, please propose and we can modify accordingly

**Comment by sukantahazra** [comment]
Just putting some structure around this for review and discussion. Will add comments later.

image

**Pull request closed without merging**
