### PR TITLE
feat(quicklinks):Adding content to quick links page

### PR DESCRIPTION
**Pull request by AnneThKu**
This PR is to add a quick links page to the website, which can be used for conferences. Please find below the screenshot of the page.

image

### CODE REVIEW

**Comment by manuignatius** [comment]
Can you add a link to wnc and swan youtube playlist as videos just like the ones for UnetStack?

**Comment by AnneThKu** [comment]
Added the videos link for WNC and SWAN. 
Also PFA the screenshots from mobile.

Quick_Links_1
Quick_Links_2
Quick_Links_3

**Review by Florie25 — DISMISSED** [review]
The mobile version looks very good. Thank you.

**Comment by manuignatius** [comment]
1. WNC - Change to Wireless Networked Communications 
2. Subnero M25M underwater modems (not MF)
3. Subnero M25M underwater modems technical specifications 

Otherwise all ok from my side

**Review by manuignatius — DISMISSED** [review]

**Review by manuignatius — APPROVED** [review]

**Pull request merged**
