### PR TITLE
Updated brochures with new dimensions

### PR DESCRIPTION
**Pull request by manuignatius**
Links
- HF: https://github.com/subnero1/subnero1.github.io/blob/brochure-update/brochures/Subnero-HF-Modems.pdf
- MF: https://github.com/subnero1/subnero1.github.io/blob/brochure-update/brochures/Subnero-MF-Modems.pdf
- MC: https://github.com/subnero1/subnero1.github.io/blob/brochure-update/brochures/Subnero-MC-Modems.pdf
- UnetStack: https://github.com/subnero1/subnero1.github.io/blob/brochure-update/brochures/UnetStack-Brochure.pdf

### CODE REVIEW

**Comment by AmyGibSubnero** [comment]
The dimensions are correct from transducer to connector, but I don't know how comfortable I am with stating that as the height as it kind of encourages people to remove the cage which is not recommended. I know the goal here is to be <300mm though. 

Otherwise, SC's look good. For MC, any change we can update the image to reflect the current design? I know that's more work, but its currently showing the atlas design version.

**Review by AmyGibSubnero — COMMENTED** [review]
The dimensions are correct from transducer to connector, but I don't know how comfortable I am with stating that as the height as it kind of encourages people to remove the cage which is not recommended. I know the goal here is to be <300mm though.

Otherwise, SC's look good. For MC, any change we can update the image to reflect the current design? I know that's more work, but its currently showing the atlas design version.

**Comment by manuignatius** [comment]
> The dimensions are correct from transducer to connector, but I don't know how comfortable I am with stating that as the height as it kind of encourages people to remove the cage which is not recommended. I know the goal here is to be <300mm though.
> 
> Otherwise, SC's look good. For MC, any change we can update the image to reflect the current design? I know that's more work, but its currently showing the atlas design version.

Sure, I will use the full length - from cage to bulkhead connector. As for MC, sure we can redesign the brochure. I have been putting it off for sometime, lets get it done. Will request for a re-review once the new brochure is ready.

**Comment by manuignatius** [comment]
Updated the MC modem borchure

**Review by AmyGibSubnero — DISMISSED** [review]
The dimensions for HF SC are not updated but other than that LGTM will approved :)

**Review by AmyGibSubnero — APPROVED** [review]

**Pull request merged**
