### PR TITLE
Fixes for landing page and embedded videos

### PR DESCRIPTION
**Pull request by AnneThKu**
- The embedded videos in all pages have been fixed to use the available `flex-video` class, which includes below pages:
   _posts/2019-07-01-Subnero-at-Oceans19.md
  _posts/2020-04-08-UnetStack-Newsletter.md
  _posts/2021-05-12-Subnero-Multi-channel-Modems.md
  oceans20/index.md
  products/swan.md
  products/wnc-m25mss3+xch.md
  solutions/index.md

- Announcement section classes added in all the media queries.

The changes can be tested from the test-repo https://subnero.com/test-products/

### CODE REVIEW

**Comment by manuignatius** [comment]
Looks good while scaling down, however, now on a big screen, the videos look huge. Any way to limit a max size?

Screen Shot 2021-05-19 at 8 06 12 PM

**Review by manuignatius — APPROVED** [review]

**Review by Florie25 — APPROVED** [review]

**Comment by AnneThKu** [comment]
@manuignatius Reduced the size of the video as shown below. The changes can be tested from the test-repo https://subnero.com/test-products/

image

**Comment by notthetup** [comment]
Found an unrelated issue, 

`categories` in the YAML frontmatter can't be a comma-separated list. It has to be either a YAML list 

```
categories : 
  - news
  - wnc
```

OR a space separate string

```
categories : wnc news
```

We are using comma separate list in two pulse articles..

_posts/2020-10-03-Subnero-at-IEEE-OES-AUV2020.md
_posts/2020-10-12-Global-Oceans-2020.md

**Comment by AnneThKu** [comment]
Fixed the categories section in the header of the pulse posts.

**Pull request merged**
