### PR TITLE
Update and rename IMDEX Asia 2019 to 2019-05-14-IMDEX Asia 2019.md

### PR DESCRIPTION
**Pull request by Florie25**
For review, thumbnail is missing, please add for me.
Photos also need to be added.
Thanks

### CODE REVIEW

**Comment by manuignatius** [comment]
Share the link to the photos of the event and I can share a thumbnail here which you will need to upload since you are the owner of this PR @Florie25. @AnneThKu can you please show @Florie25 where to add thumbnail images (images folder, just use upload file from github)

**Comment by Florie25** [comment]
https://photos.google.com/share/AF1QipPUXGU11cWZyoyrKS_r8oycaxvXQ9forqKlJ-Ds0H3JF5h6vR_V2O1EOjNV5sjDbQ?key=S3p3QXZMSW80T0RxbkN2dWc5Unk2ZVNuc2RkX3FR

**Comment by manuignatius** [comment]
Please use this one for the thumbnail
pulse-thumbnail-imdex

**Comment by manuignatius** [comment]
Please use this filename for the image: pulse-thumbnail-imdex.jpg

**Review by AnneThKu — APPROVED** [review]

**Review by notthetup — APPROVED** [review]

**Comment by AnneThKu** [comment]
The thumbnail in pulse page looks like this. Do we want to make it the same size as the other 2 before merging.

Screenshot 2019-05-28 at 6 34 12 PM

**Comment by AnneThKu** [comment]
Also do we change the title to 'Subnero at Imdex Asia 2019', instead of 'Subnero Pte Ltd at Imdex Asia 2019'. The rest of the posts in the pulse page only mention as 'Subnero'

**Comment by Florie25** [comment]
> The thumbnail in pulse page looks like this. Do we want to make it the same size as the other 2 before merging.
> 
> Screenshot 2019-05-28 at 6 34 12 PM

I think we should make the suggested change so that the format is consistent.

**Pull request merged**
