### PR TITLE
Gen4 WNC product series launch

### PR DESCRIPTION
**Pull request by manuignatius**

### CODE REVIEW

**Comment by AmyGibSubnero** [comment]
Heres my review: 
- Overall looks great! 
- I think we had this discussion when we did the SWIS page but the background image here is distracting against the title. May not be an easy way to fix :( (Image 1)
- When I come from the Products page, the header image and the section image is almost the same. Do we have any others we can use for the header? (Image 2)
- The following sentence is quite long and took me a few tries to read. _"Subnero's fourth-generation Wireless Networked Communication (WNC) series of underwater acoustic modems is designed to provide best-in-class communication performance, advanced networking and localization capabilities, and developer tools to simplify the development and deployment of underwater wireless networks._ Can we split it up?
- Are the three buttons meant to show different text? It doesn't seem to work for me. (Image 3)
- The image with BeeX robot in the background I assume is out of focus on purpose but it looks low-res than out of focus to bring your focus to the modem. Do we have one when the modem is more central? (Image 4)
- Finally this is more on the brochure, there is a white line on the left side on page two. Looks a bit unfinished. (Image 3)


Image 1:
image-1

Image 2:
image-2

Image 3:
image-3

Image 4:
image-4


Image 5:
image-5

**Comment by manuignatius** [comment]
> * Subnero's fourth-generation Wireless Networked Communication (WNC) series of underwater acoustic modems is designed to provide best-in-class communication performance, advanced networking and localization capabilities, and developer tools to simplify the development and deployment of underwater wireless networks.

1. I have modified the bg image to try and make it less distracting. At the moment, this may be the best we can do
2. Done.
3. Done.
4. Should work now
5. Unfortunately, we do not have another picture where the modem is at the center. On the ones we have, the modem is too small as compared to the vehicle and hence the focus goes to the vehicle. Hence selecting this pic.
6. Nice catch. I will replace it with a fixed brochure shortly

**Comment by manuignatius** [comment]
> > * Subnero's fourth-generation Wireless Networked Communication (WNC) series of underwater acoustic modems is designed to provide best-in-class communication performance, advanced networking and localization capabilities, and developer tools to simplify the development and deployment of underwater wireless networks.
> 
> 1. I have modified the bg image to try and make it less distracting. At the moment, this may be the best we can do
> 2. Done.
> 3. Done.
> 4. Should work now
> 5. Unfortunately, we do not have another picture where the modem is at the center. On the ones we have, the modem is too small as compared to the vehicle and hence the focus goes to the vehicle. Hence selecting this pic.
> 6. Nice catch. I will replace it with a fixed brochure shortly

6. Done.

**Review by notthetup — DISMISSED** [review]

**Comment by Florie25** [comment]
In the Applications section, there is no link taking us to the leaflet for Ripple or SUN.

**Comment by manuignatius** [comment]
I purposefully didn't add the link as we have not officially released Ripple or SUN. Their brochures are on a quick links page which is not directly linked to the website. Shall we do the links after we release them?

**Review by notthetup — APPROVED** [review]

**Pull request merged**
